---
name: "somenergia-balanc-costos"

x-repo-common:
  env_file:
    # in case you want to pass environment variables to the repo container
    - .repo.env
  volumes: &repo-common-volumes
    ".:/repo" # mount current directory at /repo

x-dbt-common:
  # reusable bits, see https://docs.docker.com/compose/compose-file/10-fragments/
  environment: &dbt-common-env # needed for ~/.dbt/profiles.yml
    DBHOST: ${SOMENERGIA_KPIS_DB_HOST}
    DBPORT: ${SOMENERGIA_KPIS_DB_PORT}
    DBUSER: ${SOMENERGIA_KPIS_DB_USER}
    DBPASSWORD: ${SOMENERGIA_KPIS_DB_PASSWORD}
    DBNAME: ${SOMENERGIA_KPIS_DB_DBNAME}

version: "3.7"
services:
  builder:
    image: "harbor.somenergia.coop/dades/somenergia-kpis-builder:latest"
    deploy:
      replicas: 0 # never start service, since it is only for build purposes
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      target: builder
      cache_from:
        - "harbor.somenergia.coop/dades/somenergia-kpis-builder:latest"
  main:
    image: "harbor.somenergia.coop/dades/somenergia-kpis-main:latest"
    deploy:
      replicas: 0 # never start service, since it is only for build purposes
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      target: main
      cache_from:
        - "harbor.somenergia.coop/dades/somenergia-kpis-builder:latest"
        - "harbor.somenergia.coop/dades/somenergia-kpis-main:latest"
  dev:
    image: "harbor.somenergia.coop/dades/somenergia-kpis-dev:latest"
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      target: dev
      cache_from:
        - "harbor.somenergia.coop/dades/somenergia-kpis-builder:latest"
        - "harbor.somenergia.coop/dades/somenergia-kpis-dev:latest"
    environment:
      <<: *dbt-common-env
    volumes:
      - *repo-common-volumes
      - python_venv_dev:/repo/.venv # mount virtualenv at /venv. See https://stackoverflow.com/a/74015989/5819113
    command: /bin/sh -c "sleep infinity" # keep container running
    networks:
      - db_nw
  dbt-deps:
    image: "harbor.somenergia.coop/dades/somenergia-kpis-dbt-deps:latest"
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      target: dbt-deps
      cache_from:
        - "harbor.somenergia.coop/dades/somenergia-kpis-builder:latest"
        - "harbor.somenergia.coop/dades/somenergia-kpis-dbt-deps:latest"
    depends_on:
      - dev
    environment:
      <<: *dbt-common-env
    volumes:
      - *repo-common-volumes
      - python_venv_dbt_deps:/repo/.venv # mount virtualenv at /venv. See https://stackoverflow.com/a/74015989/5819113
    command: bash -c "dbt docs generate --project-dir dbt_balanc && dbt docs serve --project-dir dbt_balanc --port 8050"
    ports:
      - 8050:8050

networks:
  db_nw:
    name: db_nw
volumes:
  python_venv_dev:
  python_venv_dbt_deps:
