
version: 2

sources:
  - name: erp_operational
    schema: prod_operational
    tables:
      - name: pilotatge_kpis_description
      - name: pilotatge_int_kpis
      - name: pilotatge_float_kpis

models:

  - name: pilotatge_kpis_model
    description: "Cleaned pilotatge numeric KPIs for the people"
    config:
      schema: warehouse
    columns:
      - name: value
        description: "The value of KPI"
        tests:
          - not_null

  - name: combined_pilotatge_kpis
    description: "KPIS derived from a combination of kpis"
    config:
      schema: warehouse
    columns:
      - name: value
        description: "The value of KPI"
        tests:
          - not_null
