
version: 2

sources:
  - name: erp_operational
    schema: prod_operational
    tables:
      - name: erppeek_kpis_description
      - name: pilotatge_int_kpis
      - name: pilotatge_float_kpis

models:

  - name: kpis_raw
    description: "Cleaned pilotatge numeric KPIs for the people"
    config:
      schema: warehouse
    columns:
      - name: value
        description: "The value of KPI"
        tests:
          - not_null

  - name: kpis_with_derived
    description: "KPIS expanded with derived kpis"
    config:
      schema: warehouse
    columns:
      - name: create_date
        description: "date of the creation of the kpis by airflow"
        tests:
          - not_null

  - name: kpis_bucketed_daily
    description: "All KPIS, combined and direct one kpi per day"
    config:
      schema: warehouse
    columns:
      - name: create_date
        description: "date of the creation of the kpis by airflow"
        tests:
          - not_null
          - unique