
version: 2

sources:
  - name: erp_operational
    schema: prod_operational
    tables:
      - name: erppeek_kpis_description
      - name: pilotatge_int_kpis
      - name: pilotatge_float_kpis
  - name: odoo
    schema: public
    tables:
      - name: airbyte_odoo_hr_employee
      - name: airbyte_odoo_hr_employee_calendar
      - name: airbyte_odoo_hr_department

models:

  - name: kpis_raw
    description: "Cleaned pilotatge numeric KPIs for the people"
    config:
      schema: warehouse
    columns:
      - name: value
        description: "The value of KPI"
        tests:
          - not_null

  - name: kpis_wider
    description: "KPis row wider"
    config:
      schema: warehouse
    columns:
      - name: create_date
        description: "date of the creation of the kpis by airflow"
        tests:
          - not_null

  - name: kpis_with_derived
    description: "KPIS expanded with derived kpis"
    config:
      schema: warehouse
    columns:
      - name: create_date
        description: "date of the creation of the kpis by airflow"
        tests:
          - not_null

  - name: kpis_bucketed_daily
    description: "All KPIS, combined and direct one kpi per day"
    config:
      schema: warehouse
    columns:
      - name: create_date
        description: "date of the creation of the kpis by airflow"
        tests:
          - not_null
          - unique

  - name: kpis_description
    description: "KPIs description original + names, descriptions of computed new KPIs in DBT"
    config:
      schema: warehouse
    columns:
      - name: create_date
        description: "date of the creation of the KPI description"
        tests:
          - not_null
          - unique