
version: 2

sources:
  - name: erp_operational
    schema: prod_operational
    tables:
      - name: erppeek_kpis_description
      - name: pilotatge_int_kpis
      - name: pilotatge_float_kpis

  - name: datasources
    schema: datasources
    tables:
      - name: pilotatge_int_kpis

models:

  - name: kpis_combined2
    description: "KPIS derived from a transformation of the kpis"
    config:
      schema: warehouse
    columns:
      - name: value
        description: "The value of KPI"
        tests:
          - not_null

  - name: kpis_raw
    description: "Cleaned pilotatge numeric KPIs for the people"
    config:
      schema: warehouse
    columns:
      - name: value
        description: "The value of KPI"
        tests:
          - not_null

  - name: kpis_combined
    description: "KPIS derived from a combination of kpis"
    config:
      schema: warehouse
    columns:
      - name: value
        description: "The value of KPI"
        tests:
          - not_null

  - name: kpis
    description: "All KPIS, combined and direct repeteated runs"
    config:
      schema: warehouse
    columns:
      - name: value
        description: "The value of KPI"
        tests:
          - not_null

  - name: kpis_bucketed_daily
    description: "All KPIS, combined and direct one kpi per day"
    config:
      schema: warehouse
    columns:
      - name: value
        description: "The value of KPI"
        tests:
          - not_null