
version: 2

models:

  - name: widetable_socies
    description: "Wide table de persones sòcies"

  - name: baixes_socies
    description: "Baixes de persones sòcies"
    columns:
      - name: data_baixa
        tests:
          - not_null

  - name: altes_socies
    description: "Altes de persones sòcies"

  - name: clustering