
version: 2

models:

  - name: widetable_socies
    description: "Wide table de persones sòcies"
    enabled: true
    columns:
      - name: id
        description: "id de la persona sòcia"
        tests:
          - not_null