
version: 2

sources:
  - name: datalake_erp
    tables:
      - name: somenergia_soci

models:

  - name: widetable_socies
    description: "Wide table de persones sòcies"
    enabled: true
    columns:
      - name: id
        description: "id de la persona sòcia"
        tests:
          - not_null