{{ config(materialized='view') }}
 select
 	partner_ref,
	res_partner_id,
	nom_de_pila,
	nom_complet,
	partner_vat,
	personalitat_juridica,
	phone,
	mobile,
	email,
	lang,
	partner_municipi as municipi,
	partner_comarca as comarca,
	partner_provincia as provincia,
	partner_ccaa as ccaa,
	genere,
	max(potencia) as potencia_maxima_contractada,
	case WHEN max(autoconsumo::integer) > 0 THEN TRUE ELSE FALSE END as te_autoconsum,
	count(*) as contractes,
	SUM(contracte_actiu::integer) as contractes_actius,
	case WHEN SUM(socia_activa::integer) > 0 THEN TRUE ELSE FALSE END as socia_activa,
	MAX(anys_antiguitat) as anys_antiguitat,
	data_baixa_soci,
	MAX(write_date_soci) as write_date_soci
from {{ref('dm_contractes_socies_demografia')}}
--where res_partner_id is not null
group by
	partner_ref,
	res_partner_id,
	nom_de_pila,
	nom_complet,
	partner_vat,
	personalitat_juridica,
	phone,
	mobile,
	email,
	lang,
	partner_municipi,
	partner_comarca,
	partner_provincia,
	partner_ccaa,
	genere,
	data_baixa_soci
