dbt_kpis:
  outputs:

    puppis_prod:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT') }}"
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASS') }}"
      dbname: "{{ env_var('DBT_DBNAME') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"

  target: puppis_prod
