
version: 2

sources:
  - name: erp
    tables:
      - name: somenergia_soci
      - name: giscedata_cups_ps
      - name: giscedata_polissa
      - name: giscedata_polissa_tarifa
      - name: res_comarca
      - name: res_comunitat_autonoma
      - name: res_country_state
      - name: res_municipi
      - name: res_partner
      - name: res_partner_address

models:

  - name: erp_somenergia_soci_dirty
    description: "Taules somenergia socis amb columnes de coherència"

  - name: erp_somenergia_soci
    description: "Taules somenergia socis"
    columns:
      - name: data_alta
        tests:
          - not_null
      - name: es_baixa
        tests:
          - not_null


