
version: 2

sources:
  - name: datalake_erp
    tables:
      - name: somenergia_soci

models:

  - name: erp_somenergia_soci
    description: "Taules somenergia socis"
    enabled: true
    columns:
      - name: id
        description: "id del soci"
        tests:
          - not_null