
version: 2

sources:
  - name: datalake_erp
    tables:
      - name: somenergia_soci

models:

  - name: erp_somenergia_soci
    description: "Taules somenergia socis"
    columns:
      - name: data_alta
        tests:
          - not_null
      - name: es_baixa
        tests:
          - not_null

